language: node_js
node_js:
- '8'

before_install:
  - stty cols 80

env:
  global:
  - secure: L5vNGeb6J1ny0hZ4GX5DzC4usAswY6tm6mNHURiry1O+mHA5J44I6ORjere7fumK+DMnP/7SM5TjZ54kyjgP5sfp1U713atCxjhxL4rxgCDQy9mPQkrVohubmpuzlkTGjW1N/dWLUk3+HLSo+ze++DBpwryqxQxTenlkMAtVBDuTMbaLzJ+Nr2TLaqTLp053q9vBmM0c/VFL5kfFwUO/+pbVsScVL3c0B/KKPs0OMJKyjYRSH/m+5DBgB81meAZeSzS7vcvM8W1yKv1zTBW8fUQTh4+jWAIXWz8COSoeuPSA8yHax0UJ7CkqdlzZ8qT1+hKIIuiSSnlYGtET9/UUJPVeONk2sAHayfVqBqkQiD0m/cksaiiUYUUJf/4kcLjKMJWMAnbjRpUlhQFa+KJPbDVOVWyRrVmVpkrobGAmlU9gc1Ca+ceJ1ynLncixomYuZHcIV+RDX2eqZRxPw+FvcSAx5umzVAjHrKEEqa1m06V0aUWIozhXPIsUbWyc4Kx/tJ+qAMmOo8cohgmH+HWefeKxyVvwuiyI5xZZUigX0wMYFLim4bZS1s9C0ifhdBmKgJgcv0ZB0C+8IYavoMyfmnoMuDRpuTpoi7EDlcfhvs5Ec+VFUzMz2asA3aSDDsNnOun0RivWPG4uNCmYfrzCji4t4dYv0MIILBj9l7n9X2g=
  - secure: OUGXCRBVAR5i+mAtZlisCGLwXFZr4hzU0liwWTf7I/yGG9kWJk3BOpYqCGbrHA98RkfgTeIyBYspGPPXLX46J4Z1kk/rHOmkKaYk5A4oQ8lbgzn4qQO2r5GxD/4SAUJiodV2ymUqARhb+wl8VEBud5lq+GzNmJ51nPahLl1ikYd/qve2IBeYgRwHhSVNwrpXeSQTuERxfXJvj4/GztZo7X3/VG4faLLj40RllocEuZdZX8fi1g9XNPAiOpITmJ2xuXT8FQPjhhERsSaqE5wZnabwLfQFLYjL13/taMAcKsRLBJtHOjcUuo87HG7n0KX913yi/4SF73x7WtfVtMwYnrp8z7+1u21ba3t+ClkA3NNCe8kx5UDZ6Yri9Ai1mU+uux15RDTm9GeeuHb+vKDDeE5uCYYqoYDvFFMQ8CJHunRhBR/s0unIrQFsTbE9VoIWfmS+QeSNswhKOlEwi9NcSnlh5oQb/zeptGSWW+MCHrBMWOu0ImbuWEjqaGsvsAw4mAamNENLF5MvRXJapnshC9hnTHjLa6+B+e3Zbycyd2fIyO7Yv1d1ZbMdzEFfrirS9JRHote84HpcXCKjT4a7m78Ma5l14Ce12M2FTzTMi5Cfjz33x6uiHzX36Aj/GO3l6M4r2TwVhY/lcC1/jyHVgccsYLGol5f5+Q1EGO73Vd0=
dist: trusty
sudo: required
addons:
  firefox: stable
  chrome: stable

before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3
- npm install -g concurrently@3.1.0
script:
- npm run build_knockout_dev
- npm run build_knockout_prod
- npm run build_react_dev
- npm run build_react_prod
- npm run build_angular_dev
- npm run build_angular_prod
- npm run build_jquery_dev
- npm run build_jquery_prod
- npm run build_vue_dev
- npm run build_vue_prod
- karma start --single-run
- http-server --silent &
- testcafe chrome testCafe/ --reporter minimal
#- npm run testcafe_sauce
- if [[ "$TRAVIS_EVENT_TYPE" = "cron" ]]; then echo "Starting functional tests on SauceLabs..."; npm run testcafe_sauce; fi
before_deploy: 
- tar -zcvf surveyjs.tar.gz packages
- npm run doc_gen
deploy:
- provider: releases
  api_key:
    secure: Lr8z0Dj+oakqyzK+2zQeZGW5QwprPzlXl5ODN7ajk0IRn2aTMceKgs0uk2iqO7AdyqkGrDD89NeRFlKBbiPVrsee4WRV+vf9FinDG6BRtEoHIScQzHeKlvqdSU3QtjUxdQVqwL1oa6VJYrIxdctFcKkZqh76IVzbacK9bzZavDZZQ7offhyBKP/VEPgKuYBPfCJiKI7kW0niWUztBlPbjpo1Tz1KlTTBrIBNpRka2crZ7n0eADXwyl6bA1EKx5Za2YE0pPeKnutKSymDPT147lovb+ViRkKcxT/xRu2xtzb9exsH/BB2KEOgS+llmON57jI00ntnVhDsFRiZQ6nP6sMM1qiRpkO+nu6tH4yRLptw6ekR2had+ERvaNr4SO4gvplo2RtzYufUPjbBLc40aQDu5DBeLmvTgKE4WLL8DiQ0cC7Gf+AfJRah3VtPfoQbCd2n/AkwR8yObrZDdJPwBAbpPCXNONHOK8Exmgz1Q7HDcm5BLMnTfyAjzpbZ23gtilxvtUAqUorwkDiPms3eEjWYNw5cew0hTHlavWaAt/wSKlX2Z42WgUbrCPQRGYIEL6nE9cE07HOhd0swddNS/Jx5u762ldPtOuaTkRUqDrLX0upwXSl47VHmgUAoHi8JUzPW0quUMWywH4gKdqcV5I4kYICvE6PqrXbNotseKIU=
  file:
  - surveyjs.tar.gz
  skip_cleanup: true
  on:
    tags: true
- provider: script
  script: chmod +x ./deploy_npm.sh && ./deploy_npm.sh
  skip_cleanup: true
  on:
    tags: true
- provider: script
  script: npm run doc_update
  skip_cleanup: true
  on:
    branch: master
notifications:
  email:
    recipients:
      - andrew.telnov@gmail.com
