on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Build
        run: |
          npm install
          npm run build
          
      - name: Zip Build
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r build.zip build

      - name: Create Release
        uses: taiki-e/create-gh-release-action@v1
        with:
          # (Optional)
          changelog: CHANGELOG.md
          # (Optional) Format of title.
          # [default value: $tag]
          # [possible values: variables $tag, $version, and any string]
          title: $version
          # (Required) GitHub token for creating GitHub Releases.
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add Zip Build Artifact
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'build.zip'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: $tag
